version: '3.9'

services:

  MsProjet:
    build: ./gestionconge
    image: ikramdhib/MsProjet
    container_name: congeContainer
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  eureka-server:
    build: ./EurekaServer
    image: ikram/eureka
    container_name: eurekaContainer
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  api-gateway:
    build: ./ApiGateway
    image: ikram/apigateway
    container_name: apigatewayContainer
    ports:
      - "8056:8056"
    depends_on:
      - eureka-server
      - MsProjet
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka